#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/code/dotfiles/zsh/zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/code/dotfiles/zsh/zprezto/init.zsh"
fi

# Customize to your needs...
# up
   function up_widget() {
      BUFFER="cd .."
      zle accept-line
   }
   zle -N up_widget
   bindkey "^k" up_widget

# git
   function git_prepare() {
      if [ -n "$BUFFER" ];
         then
            BUFFER="git add -A && git commit -m \"$BUFFER\" && git push"
      fi

      if [ -z "$BUFFER" ];
         then
            BUFFER="git add -A && git commit -v && git push"
      fi
            
      zle accept-line
   }
   zle -N git_prepare
   bindkey "^g" git_prepare

# Custom cd
chpwd() ls

# Aliases
alias sshdcu="ssh joycec27@student.computing.dcu.ie"
alias killkodi="kodi-send --action='Quit'"
alias sl="/usr/games/sl"

# Environment Variables
export EINSTEIN_USERNAME="joycec27"
